[tool.poetry]
name = "try github actions"
version = "0.1.0"
description = ""
authors = ["Tom Liu <tomliu6116@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytz = "^2024.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
