name: Run Python
on: 
    push:
    schedule:
        - cron: 0 0 * * * # Everyday 00:00
jobs:
    build:
        name: setup and run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: step1
              run: python3 main.py
