name: Run Python
on: 
    push:
jobs:
    build:
        name: setup and run
        runs-on: ubuntu-last
        steps:
            - uses: actions/checkout@v2
            - name: step1
                run: 
                    python3 main.py
