name: Run Python
on: 
    push:
    schedule:
        - cron: 0 0 * * 0
env:
    TZ: "Asia/Taipei"
    LOCAL_TIME: "12:00"
jobs:
    build:
        name: setup and run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: step1
              run: python3 main.py
